file = "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip"
temp <- tempfile()
download.file(file,temp)
NEI <- readRDS(unz(temp,"summarySCC_PM25.rds"))
SCC <- readRDS(unz(temp, "Source_Classification_Code.rds"))
unlink(temp)
library(dplyr)
sum_year = NEI %>% group_by(., year) %>% summarize(., sumPH25 = sum(Emissions))
plot(sum_year)
lines(sum_year)
title(main="Pollution PM25 by year")  
dev.copy(png, file = "plot1.png")  
dev.off()  