file = "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2FNEI_data.zip"
temp <- tempfile()
download.file(file,temp)
NEI <- readRDS(unz(temp,"summarySCC_PM25.rds"))
SCC <- readRDS(unz(temp, "Source_Classification_Code.rds"))
unlink(temp)
library(dplyr)
Baltimore = subset(NEI, fips == "24510")
x = group_by(Baltimore, year)
summary = summarize(x, sumPH_25 = sum(Emissions))
plot(summary)
lines(summary)
title(main="Pollution PM25 in Baltimore by year")  
dev.copy(png, file = "plot2.png")  
dev.off()  